MakaevFilmTestApp/Models/Film.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MakaevFilmTestApp.Models
{
    public class Film
    {
        public int Id { get; set; }
        public string FilmTitle { get; set; }
        public string FilmDescription { get; set; }
        public DateTime DateProduction { get; set; }
        public int Rate { get; set; }
    }
}

MakaevFilmTestApp/Controllers/ActorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MakaevFilmTestApp.Data;
using MakaevFilmTestApp.Models;
using Microsoft.AspNet.Identity;

namespace MakaevFilmTestApp.Controllers
{
    public class ActorsController : Controller
    {
        private readonly ApplicationDbContext _context;
       
        public ActorsController(ApplicationDbContext context)
        {
            _context = context;
       
        }

        // GET: Actors
        public async Task<IActionResult> Index()
        {
            string userName=(User.Identity.GetUserId());
    
            return View(await _context.Actors.ToListAsync());
        }

        // GET: Actors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actor = await _context.Actors
                .FirstOrDefaultAsync(m => m.Id == id);
            if (actor == null)
            {
                return NotFound();
            }

            return View(actor);
        }

        // GET: Actors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Actors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Lastname,Name,ActorDescription")] Actor actor)
        {
            if (ModelState.IsValid)
            {
                _context.Add(actor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(actor);
        }
     
        // GET: Actors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actor = await _context.Actors.FindAsync(id);
            if (actor == null)
            {
                return NotFound();
            }
            return View(actor);
        }

        // POST: Actors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Lastname,Name,ActorDescription")] Actor actor)
        {
            if (id != actor.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(actor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ActorExists(actor.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(actor);
        }
        public async Task<IActionResult> GetFilmActors(Film film)
        {
            var actorsParticipiations = _context.ActorsFilmParticipation.Where(x => x.FilmId == film.Id);
            List<Actor> filmActors = new List<Actor>();
            foreach (var item in actorsParticipiations)
            {
                filmActors.Add(_context.Actors.Where(x => x.Id == item.ActorId).First());
            }
            return  View("Index", filmActors);
        }
        // GET: Actors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actor = await _context.Actors
                .FirstOrDefaultAsync(m => m.Id == id);
            if (actor == null)
            {
                return NotFound();
            }

            return View(actor);
        }

        // POST: Actors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var actor = await _context.Actors.FindAsync(id);
            _context.Actors.Remove(actor);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ActorExists(int id)
        {
            return _context.Actors.Any(e => e.Id == id);
        }
    }
}

MakaevFilmTestApp/Controllers/FilmsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MakaevFilmTestApp.Data;
using MakaevFilmTestApp.Models;

namespace MakaevFilmTestApp.Controllers
{
    public class FilmsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FilmsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Films
        public async Task<IActionResult> Index()
        {
            return View("Index",await _context.Films.OrderBy(x=>x.FilmTitle).ToListAsync());
        }
        public async Task<IActionResult> ViewByPopular()
        {
            return View("Index", await _context.Films.OrderByDescending(x => x.Rate).ToListAsync());
        }
        public async Task<IActionResult> ViewByDate()
        {
            return View("Index", await _context.Films.OrderByDescending(x => x.DateProduction).ToListAsync());
        }
        public async Task<IActionResult> GetActorFilms(int id)
        {
            var filmsParticipiations = _context.ActorsFilmParticipation.Where(x => x.ActorId == id);
            List<Film> actorFilms = new List<Film>();
            foreach (var item in filmsParticipiations)
            {
                actorFilms.Add(_context.Films.Where(x => x.Id == item.FilmId).First());
            }
            return View("Index", actorFilms);
        }
        // GET: Films/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var film = await _context.Films
                .FirstOrDefaultAsync(m => m.Id == id);
            if (film == null)
            {
                return NotFound();
            }

            return View(film);
        }

        // GET: Films/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Films/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FilmTitle,FilmDescription,DateProduction")] Film film)
        {
            if (ModelState.IsValid)
            {
                _context.Add(film);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(film);
        }

        // GET: Films/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var film = await _context.Films.FindAsync(id);
            if (film == null)
            {
                return NotFound();
            }
            return View(film);
        }

        // POST: Films/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FilmTitle,FilmDescription,DateProduction")] Film film)
        {
            if (id != film.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(film);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FilmExists(film.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(film);
        }

        // GET: Films/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var film = await _context.Films
                .FirstOrDefaultAsync(m => m.Id == id);
            if (film == null)
            {
                return NotFound();
            }

            return View(film);
        }

        // POST: Films/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var film = await _context.Films.FindAsync(id);
            _context.Films.Remove(film);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FilmExists(int id)
        {
            return _context.Films.Any(e => e.Id == id);
        }
    }
}

MakaevFilmTestApp/Views/Films/Create.cshtml
@model MakaevFilmTestApp.Models.Film

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Film</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FilmTitle" class="control-label"></label>
                <input asp-for="FilmTitle" class="form-control" />
                <span asp-validation-for="FilmTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FilmDescription" class="control-label"></label>
                <input asp-for="FilmDescription" class="form-control" />
                <span asp-validation-for="FilmDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateProduction" class="control-label"></label>
                <input asp-for="DateProduction" class="form-control" />
                <span asp-validation-for="DateProduction" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MakaevFilmTestApp/Views/Films/Delete.cshtml
@model MakaevFilmTestApp.Models.Film

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Film</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FilmTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FilmTitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FilmDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FilmDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateProduction)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateProduction)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MakaevFilmTestApp/Views/Films/Details.cshtml
@model MakaevFilmTestApp.Models.Film

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Film</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FilmTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FilmTitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FilmDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FilmDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateProduction)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateProduction)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MakaevFilmTestApp/Views/Films/Edit.cshtml
@model MakaevFilmTestApp.Models.Film

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Film</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FilmTitle" class="control-label"></label>
                <input asp-for="FilmTitle" class="form-control" />
                <span asp-validation-for="FilmTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FilmDescription" class="control-label"></label>
                <input asp-for="FilmDescription" class="form-control" />
                <span asp-validation-for="FilmDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateProduction" class="control-label"></label>
                <input asp-for="DateProduction" class="form-control" />
                <span asp-validation-for="DateProduction" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MakaevFilmTestApp/Views/Films/Index.cshtml
@model IEnumerable<MakaevFilmTestApp.Models.Film>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Кнопка выпадающего списка
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <a class="dropdown-item" asp-action="Index" >По алфавиту</a>
        <a class="dropdown-item" asp-action="ViewByPopular">По популярности</a>
        <a class="dropdown-item" asp-action="ViewByDate">По дате выхода в прокат</a>
    </div>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FilmTitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FilmDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateProduction)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FilmTitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FilmDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateProduction)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                <a asp-controller="Actors" asp-action="GetFilmActors" asp-route-id="@item.Id">Актёры</a>
            </td>
        </tr>
}
    </tbody>
</table>