MakaevFilmTestApp/ViewModels/ActorLike.cs
using MakaevFilmTestApp.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MakaevFilmTestApp.ViewModels
{
    public class ActorLike
    {
        public int Id { get; set; }
        
        public int ActorId { get; set; }
        [NotMapped]
        public Actor Actor { get; set; }
        public string UserId { get; set; }
        public bool Like { get; set; }
    }
}

MakaevFilmTestApp/Controllers/ActorLikesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MakaevFilmTestApp.Data;
using MakaevFilmTestApp.ViewModels;
using Microsoft.AspNet.Identity;

using System.Security.Claims;
using MakaevFilmTestApp.Models;

namespace MakaevFilmTestApp.Controllers
{
    public class ActorLikesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private string userId;
        private List<ActorLike> actorLikes = new List<ActorLike>();
        public ActorLikesController(ApplicationDbContext context)
        {
            _context = context;

        }


        public bool checkOnLike(string userId, int actorId)
        {
            var likeOnActor = (_context.ActorLike.FirstOrDefault(x => x.ActorId == actorId && x.UserId == userId));
            if (likeOnActor == null)
            {
                return false;
            }
            else
            {
               
                return likeOnActor.Like;
            }
        }
        // GET: ActorLikes

        public async Task<IActionResult> Index()
        {
            try
            {
                userId = (User.Identity.GetUserId());

            }
            catch
            {
                userId = null;
            }
            ViewData["userId"] = userId;
            var actors = _context.Actors;
            foreach (var item in actors)
            {
                //like - value like it on actor or not
                bool like = checkOnLike(userId, item.Id);
                int rate = _context.ActorLike.Where(x => x.ActorId == item.Id && x.Like == true).Count();
                item.Rate = rate;
                actorLikes.Add(new ActorLike { ActorId = item.Id, Actor = item, Like = like });
            }
            return View("Index",actorLikes.OrderBy(x => x.Actor.Lastname));
        }

   
        public async Task<IActionResult> ViewByPopular()
        {
            try
            {
                userId = (User.Identity.GetUserId());

            }
            catch
            {
                userId = null;
            }
            ViewData["userId"] = userId;
            var actors = _context.Actors;
            foreach (var item in actors)
            {
                //like - value like it on actor or not
                bool like = checkOnLike(userId, item.Id);
                int rate = _context.ActorLike.Where(x => x.ActorId == item.Id).Count();
                item.Rate = rate;
                actorLikes.Add(new ActorLike { ActorId = item.Id, Actor = item, Like = like });
            }
            return View("Index",actorLikes.OrderByDescending(x => x.Actor.Rate));
        }
        // GET: ActorLikes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actorLike = await _context.Actors
                .FirstOrDefaultAsync(m => m.Id == id);
            if (actorLike == null)
            {
                return NotFound();
            }

            return View("~/Views/Actors/Details.cshtml",actorLike);
        }

        // GET: ActorLikes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ActorLikes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ActorId,UserId,Like")] ActorLike actorLike)
        {
            if (ModelState.IsValid)
            {
                _context.Add(actorLike);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(actorLike);
        }

        // GET: ActorLikes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actorLike = await _context.ActorLike.FindAsync(id);
            if (actorLike == null)
            {
                return NotFound();
            }
            return View(actorLike);
        }

        // POST: ActorLikes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ActorId,UserId,Like")] ActorLike actorLike)
        {
            if (id != actorLike.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(actorLike);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ActorLikeExists(actorLike.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(actorLike);
        }

        // GET: ActorLikes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actorLike = await _context.ActorLike
                .FirstOrDefaultAsync(m => m.Id == id);
            if (actorLike == null)
            {
                return NotFound();
            }

            return View(actorLike);
        }

        // POST: ActorLikes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var actorLike = await _context.ActorLike.FindAsync(id);
            _context.ActorLike.Remove(actorLike);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        [HttpPost]
        public ActionResult LikeSet(int actorId)
        {
            userId = (User.Identity.GetUserId());
            var actor = _context.Actors.FirstOrDefault(x => x.Id == actorId);
            var searchingRecord = _context.ActorLike.FirstOrDefault(x => x.ActorId == actorId && x.UserId == userId);
            if (searchingRecord == null)
            {
                ActorLike actorLike = new ActorLike { ActorId = actorId,Actor=actor, UserId = userId, Like = true };
                _context.ActorLike.Add(actorLike);
                int iii = actorLike.Id;
                _context.SaveChanges();
            }
            else
            {
                searchingRecord.Like = !searchingRecord.Like;
            }
            _context.SaveChangesAsync();

            return View("Index");
        }
        [HttpPost]
        public string AjaxTest(ActorLike obj)
        {

            int actorId = obj.ActorId;
            LikeSet(actorId);
            return "Test";
        }
        private bool ActorLikeExists(int id)
        {
            return _context.ActorLike.Any(e => e.Id == id);
        }
    }
    public class LogOnModel
    {
        public string Mobile { get; set; }
        public string EmailID { get; set; }
    }

}

MakaevFilmTestApp/Controllers/FilmsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MakaevFilmTestApp.Data;
using MakaevFilmTestApp.Models;

namespace MakaevFilmTestApp.Controllers
{
    public class FilmsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FilmsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Films
        public async Task<IActionResult> Index()
        {
            return View("Index",await _context.Films.OrderBy(x=>x.FilmTitle).ToListAsync());
        }
        public async Task<IActionResult> ViewByPopular()
        {
            return View("Index", await _context.Films.OrderByDescending(x => x.Rate).ToListAsync());
        }
        public async Task<IActionResult> ViewByDate()
        {
            return View("Index", await _context.Films.OrderByDescending(x => x.DateProduction).ToListAsync());
        }
        public async Task<IActionResult> GetActorFilms(int id)
        {
            var filmsParticipiations = _context.ActorsFilmParticipation.Where(x => x.ActorId == id);
            List<Film> actorFilms = new List<Film>();
            foreach (var item in filmsParticipiations)
            {
                actorFilms.Add(_context.Films.Where(x => x.Id == item.FilmId).First());
            }
            return View("Index", actorFilms);
        }
        // GET: Films/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var film = await _context.Films
                .FirstOrDefaultAsync(m => m.Id == id);
            if (film == null)
            {
                return NotFound();
            }

            return View(film);
        }

        // GET: Films/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Films/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FilmTitle,FilmDescription,DateProduction")] Film film)
        {
            if (ModelState.IsValid)
            {
                _context.Add(film);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(film);
        }

        // GET: Films/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var film = await _context.Films.FindAsync(id);
            if (film == null)
            {
                return NotFound();
            }
            return View(film);
        }

        // POST: Films/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FilmTitle,FilmDescription,DateProduction")] Film film)
        {
            if (id != film.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(film);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FilmExists(film.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(film);
        }

        // GET: Films/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var film = await _context.Films
                .FirstOrDefaultAsync(m => m.Id == id);
            if (film == null)
            {
                return NotFound();
            }

            return View(film);
        }

        // POST: Films/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var film = await _context.Films.FindAsync(id);
            _context.Films.Remove(film);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FilmExists(int id)
        {
            return _context.Films.Any(e => e.Id == id);
        }
    }
}

MakaevFilmTestApp/Views/ActorLikes/Create.cshtml
@model MakaevFilmTestApp.ViewModels.ActorLike

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>ActorLike</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ActorId" class="control-label"></label>
                <input asp-for="ActorId" class="form-control" />
                <span asp-validation-for="ActorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <input asp-for="UserId" class="form-control" />
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Like" /> @Html.DisplayNameFor(model => model.Like)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MakaevFilmTestApp/Views/ActorLikes/Delete.cshtml
@model MakaevFilmTestApp.ViewModels.ActorLike

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ActorLike</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ActorId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ActorId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Like)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Like)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MakaevFilmTestApp/Views/ActorLikes/Details.cshtml
@model MakaevFilmTestApp.ViewModels.ActorLike

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ActorLike</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ActorId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ActorId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Like)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Like)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MakaevFilmTestApp/Views/ActorLikes/Edit.cshtml
@model MakaevFilmTestApp.ViewModels.ActorLike

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ActorLike</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="ActorId" class="control-label"></label>
                <input asp-for="ActorId" class="form-control" />
                <span asp-validation-for="ActorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <input asp-for="UserId" class="form-control" />
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Like" /> @Html.DisplayNameFor(model => model.Like)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MakaevFilmTestApp/Views/ActorLikes/Index.cshtml
@model IEnumerable<MakaevFilmTestApp.ViewModels.ActorLike>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Сортировка
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <a class="dropdown-item" asp-action="Index">По алфавиту</a>
        <a class="dropdown-item" asp-action="ViewByPopular">По популярности</a>

    </div>
</div>
<table class="table">
    <thead>
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.ActorId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Like)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ActorId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Actor.Lastname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Actor.ActorDescription)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserId)
                </td>
                <td class="actor_rate">
                    @Html.DisplayFor(modelItem => item.Actor.Rate)
                </td>
                <td>
                    @if (ViewData["userId"] != null)
                    {
                        @if (item.Like)
                        {
                            <div class="like_on like_area" value="@item.ActorId"></div>
                        }
                        else
                        {
                            <div class="like_off like_area" value="@item.ActorId"></div>
                        }
                    }
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.ActorId">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    <a asp-controller="Films" asp-action="GetActorFilms" asp-route-id="@item.ActorId">Фильмы в которых снимался актёр</a>
                </td>
            </tr>
        }
    </tbody>

</table>
<div id="output"></div>
<script type="text/javascript">
    $(document).ready(function () {
        $(".like_area").click(function () {
            var activeElement = $(this);
            console.log(activeElement);
            var actorLike = {
                ActorId: activeElement.attr("value") 
            };
            console.log(activeElement.attr("value"));
            $.ajax({
                url: '@Url.Action("AjaxTest", "ActorLikes")', // try to use Url Helper when possible
                type: 'POST', // use Get for [HttpGet] action or POST for [HttpPost]
                //contentType: 'application/json', not needed
                //dataType: 'jsonp', jsonp is for sending to a site other than the current one..
                data: actorLike, // no need to stringify
                success: function (result) {
                  
                    changeLikeImage(activeElement);
                   
                }
            });

        });
    });
    function changeLikeImage(element) {
        var likeOn = "like_on";
        var likeOff = "like_off";
        var actorRateDiv=element.parent().parent().children("td.actor_rate");
        if (element.hasClass(likeOn)) {
            element.removeClass(likeOn);
            element.addClass(likeOff);
            actorRateDiv.html(parseInt(actorRateDiv.html()) - 1);
        } else {
            element.removeClass(likeOff);
            element.addClass(likeOn);
            actorRateDiv.html(parseInt(actorRateDiv.html()) + 1)
        }
        
    }
</script>